classes:
- system.linux.system.repo.docker_legacy
- system.kubernetes.pool.cluster
- system.salt.minion.cert.k8s_client
- system.salt.minion.cert.etcd_client
- cluster.virtual-mcp11-k8s-calico
parameters:
  docker:
    host:
      pkgs:
        - ${_param:kubernetes_docker_package}
        - python-docker
  kubernetes:
    pool:
      network:
        etcd:
          ssl:
            enabled: true
        image: ${_param:kubernetes_calico_image}
        calicoctl:
          image: ${_param:kubernetes_calicoctl_image}
        cni:
          image: ${_param:kubernetes_calico_cni_image}
        mtu: ${_param:kubernetes_mtu}
    common:
      addons:
        virtlet:
          enabled: ${_param:kubernetes_virtlet_enabled}
          namespace: kube-system
          image: ${_param:kubernetes_virtlet_image}
          hosts:
          - ${_param:kubernetes_compute_node01_hostname}
          - ${_param:kubernetes_compute_node02_hostname}
      hyperkube:
        image: ${_param:kubernetes_hyperkube_image}
  linux:
    network:
      resolv:
        dns:
          - 10.254.0.10
      interface:
        ens4:
          route:
            kubernetes_services:
              address: 10.254.0.0
              netmask: 255.255.0.0
              gateway: ${_param:single_address}
      interface:
        ens4:
          route:
            kubernetes_services:
              address: 10.254.0.0
              netmask: 255.255.0.0
              gateway: ${_param:single_address}
