---
driver:
  name: docker
  use_sudo: false
  volume:
    - <%= ENV['PWD'] %>:/tmp/kitchen

provisioner:
  name: shell
  script: verify.sh

platforms:
  <% `find classes/cluster -maxdepth 1 -mindepth 1 -type d | tr '_' '-' |sort -u`.split().each do |cluster| %>
  <% cluster=cluster.split('/')[2] %>
  - name: <%= cluster %>
    driver_config:
      #image: ubuntu:16.04
      image: tcpcloud/salt-models-testing # With preinstalled dependencies (faster)
      platform: ubuntu
      hostname: cfg01.<%= cluster %>.local
      provision_command:
        - apt-get update
        - apt-get install -y git curl python-pip
        - pip install --upgrade pip
        - git clone https://github.com/salt-formulas/salt-formulas-scripts /srv/salt/scripts
        - cd /srv/salt/scripts; git pull -r; cd -
        # NOTE: Configure ENV options as needed, example:
        - echo "
            export BOOTSTRAP=1;\n
            export CLUSTER_NAME=<%= cluster %>;\n
            export FORMULAS_SOURCE=pkg;\n
            export RECLASS_VERSION=master;\n
            export RECLASS_IGNORE_CLASS_NOTFOUND=True;\n
            export RECLASS_IGNORE_CLASS_REGEXP='service.*';\n
            export EXTRA_FORMULAS="";\n
          " > /kitchen.env
          #export RECLASS_SOURCE_PATH=/usr/lib/python2.7/site-packages/reclass;\n
          #export PYTHONPATH=$RECLASS_SOURCE_PATH:$PYTHONPATH;\n
  <% end %>

suites:
  - name: cluster

