classes:
- service.etcd.server.cluster
- system.haproxy.proxy.listen.kubernetes.apiserver
- system.linux.system.repo.docker_legacy
- system.salt.minion.cert.etcd_server
- system.kubernetes.master.cluster
- cluster.k8s-ha-calico-syndic.kubernetes.compute
- cluster.k8s-ha-calico-syndic
parameters:
  _param:
    keepalived_vip_interface: ${_param:primary_interface}
    keepalived_vip_virtual_router_id: 60
  etcd:
    server:
      source:
        engine: docker_hybrid
      ssl:
        enabled: true
      setup:
        calico:
          key: /calico/v1/ipam/v4/pool/${_param:calico_private_network}-${_param:calico_private_netmask}
          value: '{"masquerade":true,"cidr":"${_param:calico_private_network}/${_param:calico_private_netmask}"}'
  kubernetes:
    common:
      addons:
        netchecker:
          enabled: true
        helm:
          enabled: true
        coredns:
          enabled: ${_param:kubernetes_coredns_enabled}
        externaldns:
          enabled: ${_param:kubernetes_externaldns_enabled}
          image: ${_param:kubernetes_externaldns_image}
          provider: ${_param:kubernetes_externaldns_provider}
    master:
      etcd:
        ssl:
          enabled: true
      network:
        etcd:
          ssl:
            enabled: true
      namespace:
        netchecker:
          enabled: true
