parameters:
  _param:
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    salt_minion_ca_authority: salt_master_ca

    # kubernetes settings
    kubernetes_admin_user: admin
    kubernetes_admin_password: sbPfel23ZigJF3Bm
    kubernetes_admin_token: PpP6Mm3pAoPVqcKOKUu0x1dh7b1959Fi
    kubernetes_kubelet_token: JJ2PKHxjiU6EYvIt18BqwdSK1HvWh8pt
    kubernetes_kube-proxy_token: jT0hJk9L6cIw5UpYDNhsRwcj3Z2n62B6
    kubernetes_scheduler_token: VgkUHfrW07zNxrb0ucFyX7NBnSJN9Xp6
    kubernetes_controller-manager_token: uXrdZ1YKF6qlYm3sHje2iEXMGAGDWOIU
    kubernetes_dns_token: 0S1I4iJeFjq5fopPwwCwTp3xFpEZfeUl
    etcd_initial_token: IN7KaRMSo3xkGxkjAAPtkRkAgqN4ZNRq

    # docker package version
    kubernetes_docker_package: docker-engine=1.12.6-0~ubuntu-xenial

    # component docker images
    kubernetes_calicoctl_image: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico/ctl:latest
    kubernetes_calico_image: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico/node:latest
    kubernetes_calico_cni_image: docker-prod-virtual.docker.mirantis.net/mirantis/projectcalico/calico/cni:latest
    kubernetes_calico_policy_image: calico/kube-policy-controller:v0.5.4

    kubernetes_hyperkube_image: docker-prod-virtual.docker.mirantis.net/mirantis/kubernetes/hyperkube-amd64:v1.8.5-4
    kubernetes_virtlet_image: mirantis/virtlet:latest
    kubernetes_netchecker_agent_image: mirantis/k8s-netchecker-agent:stable
    kubernetes_netchecker_server_image: mirantis/k8s-netchecker-server:stable
    kubernetes_netchecker_agent_probeurls: "http://ipinfo.io"

    # switches of addons
    kubernetes_addon_namespace: kube-system
    kubernetes_dashboard: false
    kubernetes_helm_enabled: true
    kubernetes_netchecker_enabled: true
    kubernetes_calico_policy_enabled: false
    kubernetes_virtlet_enabled: false

    # addresses and hostnames
    kubernetes_internal_api_address: 10.254.0.1
    kubernetes_control_node01_hostname: ctl01
    kubernetes_control_node01_address: 172.16.10.101
    master_address: ${_param:kubernetes_control_node01_address}

    cluster_local_address: ${_param:single_address}

    # cert
    control_address: ${_param:kubernetes_control_node01_address}
    salt_master_base_environment: prd

    # etcd stuff
    node_hostname: ${_param:kubernetes_control_node01_hostname}
    node_address: ${_param:kubernetes_control_node01_address}
    node_port: 4001

    # calico
    calico_private_network: 192.168.0.0
    calico_private_netmask: 16

    # component docker images
    kubernetes_externaldns_image: mirantis/external-dns:latest
    kubernetes_externaldns_provider: coredns

    # switches of addons
    kubernetes_coredns_enabled: false
    kubernetes_externaldns_enabled: false

  linux:
    network:
      host:
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
